project:
  type: website

website:
  title: "Fred Clarke"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Exploration
        href: exploration/index.qmd
    right: 
      - icon: github
        href: https://github.com/fclarke1
      - icon: linkedin
        href: https://www.linkedin.com/in/clarkefred/
  page-footer: 
    left: "Copyright 2024, Fred Clarke" 
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

